app/routes.php
<?php

# CSRF Protection
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Static Pages. Redirecting admin so admin cannot access these pages.
Route::group(['before' => 'redirectAdmin'], function()
{
	Route::get('/', ['as' => 'home', 'uses' => 'PagesController@getHome']);
	Route::get('/about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
	Route::get('/contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
});

//belum dicobain
# Static Pages. Redirecting operator so operator cannot access these pages.
Route::group(['before' => 'redirectOperator'], function()
{
	Route::get('/', ['as' => 'home', 'uses' => 'PagesController@getHome']);
	Route::get('/about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
	Route::get('/contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
});

# Registration
Route::group(['before' => 'guest'], function()
{
	Route::get('/register', 'RegistrationController@create');
	Route::post('/register', ['as' => 'registration.store', 'uses' => 'RegistrationController@store']);
});

# Authentication
Route::get('login', ['as' => 'login', 'uses' => 'SessionsController@create'])->before('guest');
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
Route::resource('sessions', 'SessionsController' , ['only' => ['create','store','destroy']]);

# Forgotten Password //belum harus pake email. config>mail
Route::group(['before' => 'guest'], function()
{
	Route::get('forgot_password', 'RemindersController@getRemind');
	Route::post('forgot_password','RemindersController@postRemind');
	Route::get('reset_password/{token}', 'RemindersController@getReset');
	Route::post('reset_password/{token}', 'RemindersController@postReset');
});


# Alumni Routes
Route::group(['before' => 'auth|alumni'], function()
{
    //Route::get('/', ['as' => 'alumni_dashboard', 'uses' => 'AlumniController@getUserProtected']);
    Route::get('lowongan', ['as' => 'lowongan', 'uses' => 'AlumniController@getLowongan']);
    Route::get('sekolah', ['as' => 'sekolah', 'uses' => 'AlumniController@getSekolah']);
    Route::resource('profiles', 'AlumniUsersController', ['only' => ['show', 'edit', 'update']]);
    Route::get('profiles/{id}/editb', ['as' => 'editb', 'uses' => 'AlumniUsersController@editb']);
    Route::patch('profiles/{id}/updateb', ['as' => 'updateb', 'uses' => 'AlumniUsersController@updateb']);


});

# Admin Routes
Route::group(['before' => 'auth|admin'], function()
{
	Route::get('/admin', ['as' => 'admin_dashboard', 'uses' => 'AdminController@getHome']);

    Route::resource('admin/profiles', 'AdminUsersController', ['only' => ['index', 'show', 'edit', 'update', 'destroy','create','store']]);
    
    Route::resource('admin/sekolah', 'AdminSekolahController', ['only' => ['index', 'create','store','show','edit','update']]);

    Route::get('admin/jurusan/createoperator/{id}', array('as'=>'admin.jurusan.createoperator', 'uses' => 'AdminJurusanController@createOperator'));
    Route::post('admin/jurusan/storeoperator/{ids}', array('as'=>'admin.jurusan.storeoperator', 'uses'=>'AdminJurusanController@storeOperator'));
    Route::get('admin/jurusan/editoperator/{id}', array('as'=>'admin.jurusan.editoperator','uses' => 'AdminJurusanController@editOperator'));
    Route::patch('admin/jurusan/updateoperator/{id}', array('as'=>'admin.jurusan.updateoperator','uses' => 'AdminJurusanController@updateOperator'));
    Route::resource('admin/jurusan', 'AdminJurusanController', ['only' => ['show','edit','update']]);    
    Route::get('admin/jurusan/create/{id}', array('as'=>'admin.jurusan.create', 'uses' => 'AdminJurusanController@create'));
    Route::post('admin/jurusan/store/{id}', array('as'=>'admin.jurusan.store', 'uses'=>'AdminJurusanController@store'));
    Route::get('admin/jurusan/detail/{id}', array('as'=>'admin.jurusan.detail', 'uses' => 'AdminJurusanController@detail'));

    Route::resource('admin/alumni', 'AdminAlumniController', ['only' => ['show','edit','update']]);
    Route::get('admin/alumni/create/{id}', array('as'=>'admin.alumni.create', 'uses' => 'AdminAlumniController@create'));
    Route::post('admin/alumni/store/{id}', array('as'=>'admin.alumni.store', 'uses'=>'AdminAlumniController@store'));    
    Route::get('admin/alumni/detail/{id}', array('as'=>'admin.alumni.detail', 'uses' => 'AdminAlumniController@detail'));

    //ada bug kalo ditaro dibawah AdminLokerController@show
    Route::get('admin/loker/createglobal', array('as'=>'admin.loker.createglobal', 'uses' => 'AdminLokerController@createGlobal'));
    Route::post('admin/loker/storeglobal', array('as'=>'admin.loker.storeglobal', 'uses'=>'AdminLokerController@storeGlobal'));
    Route::resource('admin/loker', 'AdminLokerController', ['only' => ['index','show','edit','update']]);
    Route::get('admin/loker/create/{id}', array('as'=>'admin.loker.create', 'uses' => 'AdminLokerController@create'));
    Route::post('admin/loker/store/{id}', array('as'=>'admin.loker.store', 'uses'=>'AdminLokerController@store'));
    Route::get('admin/loker/detail/{id}', array('as'=>'admin.loker.detail', 'uses'=>'AdminLokerController@detail'));

});

# Operator Routes
Route::group(['before' => 'auth|operator'], function()
{
    Route::get('/operator', ['as' => 'operator_dashboard', 'uses' => 'OperatorController@getHome']);
    Route::resource('operator/profiles', 'OperatorUsersController', ['only' => ['index', 'show', 'edit', 'update', 'destroy']]);
    Route::resource('operator/lowongan', 'OperatorLowonganController', ['only' => ['index', 'create','store','show','edit','update']]);
    Route::get('operator/lowongan/deactive/{id}', ['as'=>'deactivelowongan', 'uses'=>'OperatorLowonganController@deactive']);
    Route::get('operator/pending', ['as'=>'pendinguser','uses'=>'OperatorUsersController@pending']);
    Route::get('operator/approval/{id}/{user}', ['as'=>'approveuser','uses'=>'OperatorUsersController@approval']);
    Route::get('operator/decline/{id}/{user}', ['as'=>'declineuser','uses'=>'OperatorUsersController@decline']);
});

app/controllers/operator/OperatorController.php
<?php

class OperatorController extends \BaseController
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function getHome()
    {
        return View::make('protected.operator.operator_dashboard');
    }

    public function getLowongan()
    {
        $listalumni = Alumni::where('user_id', '=', Sentry::getUser()->id)->get();
        $listjurusan = Jurusan::where('id', '=', $listalumni[0]->jurusan_id)->get();
        $listlowongan = LowonganKerja::where('sekolah_id', '=', $listjurusan[0]->sekolah_id)->get();
        return View::make('protected.operator.lowongan', compact('listlowongan'));
    }


}

app/controllers/operator/OperatorLowonganController.php
<?php

class OperatorLowonganController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        
        //$listsekolah = UserSekolah::where('operator_id', '=', Sentry::getUser()->id)->
        //    get();
        
            
        $listsekolah = DB::table('mastersekolah')
                        ->join('users_sekolah','mastersekolah.id','=','users_sekolah.sekolah_id')
                        ->select('users_sekolah.sekolah_id')
                        ->where('users_sekolah.operator_id','=',Sentry::getUser()->id)
                        ->get();
            
            $listlowongan = LowonganKerja::where('sekolah_id', '=', $listsekolah[0]->sekolah_id)->where('aktif','=','1')->orderBy('id','desc')->
            get();
        
        return View::make('protected.operator.list_lowongan', compact('listlowongan'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('protected.operator.create_lowongan');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $rules = array(
            'instansi' => 'required|max:100',
            'posisi' => 'required|max:50',
            'deskripsi' => 'required');

        if (Input::has('link'))
        {
            $input = array(
                'instansi' => Input::get('instansi'),
                'link' => Input::get('link'),
                'posisi' => Input::get('posisi'),
                'deskripsi' => Input::get('deskripsi'));
        }
        else
        {
            $input = array(
                'instansi' => Input::get('instansi'),
                'posisi' => Input::get('posisi'),
                'deskripsi' => Input::get('deskripsi'));
        }
        $v = Validator::make($input, $rules);

        if ($v->fails())
        {
            return Redirect::to('operator/lowongan');
        }
        else
        {
            $listsekolah = UserSekolah::where('operator_id', '=', Sentry::getUser()->id)->
                get();

            $lowongan = new LowonganKerja;
            $lowongan->instansi = Input::get('instansi');
            $lowongan->sekolah_id = $listsekolah[0]->sekolah_id;
            $lowongan->posisi = Input::get('posisi');
            $lowongan->deskripsi = Input::get('deskripsi');
            $lowongan->createdby = Sentry::getUser()->id;
            $lowongan->lastmodifiedby = Sentry::getUser()->id;
            $lowongan->created_at = new Datetime;
            $lowongan->updated_at = new Datetime;
            $lowongan->aktif = '1';
            if(Input::has('link')){
                $lowongan->link = Input::get('link');
            }
            }
        $lowongan->save();
        
        return Redirect::to('operator/lowongan');

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $lowongan = LowonganKerja::find($id);
        return View::make('protected.operator.edit_lowongan', compact('lowongan'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        $rules = array(
            'instansi' => 'required|max:100',
            'posisi' => 'required|max:50',
            'deskripsi' => 'required');

        if (Input::has('link'))
        {
            $input = array(
                'instansi' => Input::get('instansi'),
                'link' => Input::get('link'),
                'posisi' => Input::get('posisi'),
                'deskripsi' => Input::get('deskripsi'));
        }
        else
        {
            $input = array(
                'instansi' => Input::get('instansi'),
                'posisi' => Input::get('posisi'),
                'deskripsi' => Input::get('deskripsi'));
        }
        $v = Validator::make($input, $rules);

        if ($v->fails())
        {
            return Redirect::to('operator/lowongan');
        }
        else
        {
            $listsekolah = UserSekolah::where('operator_id', '=', Sentry::getUser()->id)->
                get();

            $lowongan = LowonganKerja::find($id);
            $lowongan->instansi = Input::get('instansi');            
            $lowongan->posisi = Input::get('posisi');
            $lowongan->deskripsi = Input::get('deskripsi');            
            $lowongan->lastmodifiedby = Sentry::getUser()->id;            
            $lowongan->updated_at = new Datetime;
            $lowongan->link = Input::get('link');
            }
        $lowongan->save();
        
        return Redirect::to('operator/lowongan');
        
        }       
        
    public function deactive($id)
    {
        $lowongan = LowonganKerja::find($id);
        $lowongan->aktif = '0';
        $lowongan->save();
        return Redirect::to('operator/lowongan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }


}

app/views/protected/operator/create_lowongan.blade.php
@extends('protected.operator.master')

@section('title', 'Tambahkan Lowongan Baru')

@section('content')


		<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Tambah Lowongan</h3>
				 	</div>
				  	<div class="panel-body">
				    	{{ Form::open(['route' => 'operator.lowongan.store']) }}
	                    <fieldset>
	                    	@if (Session::has('flash_message'))
								<div class="form-group">
									<p>{{ Session::get('flash_message') }}</p>
								</div>
							@endif

							<div class="form-group">
								{{ Form::text('instansi', null, ['placeholder' => 'Nama Instansi', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('nama', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('posisi', null, ['placeholder' => 'Posisi', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('alamat', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::textarea('deskripsi', null, ['placeholder' => 'Deskripsi Pekerjaan', 'class' => 'form-control', 'required' => 'required', 'size' =>'1x5'])}}
								{{ errors_for('telepon', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('link', null, ['placeholder' => 'http:\\contoh.com\lowongan\kerja', 'class' => 'form-control'])}}
								{{ errors_for('akreditasi', $errors) }}
							</div>
                            
                            <!-- Submit field -->
							<div class="form-group">
								{{ Form::submit('Tambah', ['class' => 'btn btn-lg btn-primary btn-block']) }}
								{{ HTML::link('operator/lowongan', 'Back',['class' => 'btn btn-lg btn-info btn-block']) }}
							</div>
                            
				    	</fieldset>
				      	{{ Form::close() }}
				    </div>
				</div>
			</div>
		</div>
	</div>



@stop

app/views/protected/operator/edit_lowongan.blade.php
@extends('protected.admin.master')

@section('title', 'Edit Lowongan')

@section('content')
<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Edit Lowongan</h3>
				 	</div>
				  	<div class="panel-body">
                    
        @if (Session::has('flash_message'))
		<div class="form-group">
			<p style="padding: 5px" class="bg-success">{{ Session::get('flash_message') }}</p>
		</div>
	@endif

	{{ Form::model($lowongan, ['method' => 'PATCH', 'route' => ['operator.lowongan.update', $lowongan->id]]) }}

	<div class="form-group">
		{{ Form::label('instansi', 'Instansi:') }}
		{{ Form::text('instansi', null, ['class' => 'form-control']) }}
		{{ errors_for('instansi', $errors) }}
	</div>

	<div class="form-group">
		{{ Form::label('posisi', 'Posisi:') }}
		{{ Form::text('posisi', null, ['class' => 'form-control'])}}
		{{ errors_for('posisi', $errors) }}
	</div>

	<div class="form-group">
		{{ Form::label('deskripsi', 'Deskripsi:') }}
		{{ Form::textarea('deskripsi', null, ['class' => 'form-control'])}}
		{{ errors_for('deskripsi', $errors) }}
	</div>

	<div class="form-group">
		{{ Form::label('link', 'Link:') }}
		{{ Form::text('link', null, ['class' => 'form-control'])}}
		{{ errors_for('link', $errors) }}
	</div>

	<!-- Update Profile Field -->
	<div class="form-group">
		{{ Form::submit('Update Lowongan', ['class' => 'btn btn-primary']) }}
        {{ HTML::link('operator/lowongan', 'Back',['class' => 'btn btn-info']) }}
	</div>

	{{ Form::close() }}
    </div>
				</div>
			</div>
		</div>
	</div>

@stop

app/views/protected/operator/edit_user.blade.php
@extends('protected.operator.master')

@section('title', 'Edit Profile')

@section('content')
	<h1>Edit Profile</h1>

	@if (Session::has('flash_message'))
		<div class="form-group">
			<p style="padding: 5px" class="bg-success">{{ Session::get('flash_message') }}</p>
		</div>
	@endif

	{{ Form::model($user, ['method' => 'PATCH', 'route' => ['operator.profiles.update', $user->id]]) }}

		<div class="form-group">
			{{ Form::label('account_type', 'Account Type:') }}
			{{ Form::select('account_type', $groups, $user_group, ['class' => 'form-control']) }}
			{{ errors_for('account_type', $errors) }}
		</div>

		<!-- email Field -->
		<div class="form-group">
			{{ Form::label('email', 'Email:') }}
			{{ Form::email('email', null, ['class' => 'form-control']) }}
			{{ errors_for('email', $errors) }}
		</div>


		<!-- first_name Field -->
		<div class="form-group">
			{{ Form::label('first_name', 'First Name:') }}
			{{ Form::text('first_name', null, ['class' => 'form-control']) }}
			{{ errors_for('first_name', $errors) }}
		</div>

		<!-- last_name Field -->
		<div class="form-group">
			{{ Form::label('last_name', 'Last Name:') }}
			{{ Form::text('last_name', null, ['class' => 'form-control']) }}
			{{ errors_for('last_name', $errors) }}

		</div>

		<!-- Password field -->
		<div class="form-group">
			{{ Form::label('password', 'Password:') }}
			{{ Form::password('password', ['class' => 'form-control']) }}
			<p class="help-block">Leave password blank to NOT edit the password.</p>
			{{ errors_for('password', $errors) }}
		</div>

		<!-- Password Confirmation field -->
		<div class="form-group">
			{{ Form::label('password_confirmation', 'Repeat Password:') }}
			{{ Form::password('password_confirmation', ['class' => 'form-control'] )}}
		</div>


		<!-- Update Profile Field -->
		<div class="form-group">
			{{ Form::submit('Update Profile', ['class' => 'btn btn-primary']) }}
		</div>
	{{ Form::close() }}

@stop

app/views/protected/operator/list_lowongan.blade.php
@extends('protected.operator.master')

@section('title', 'List Lowongan Pekerjaan')

@section('content')

<h2>Daftar Lowongan</h2>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>Instansi</th>
			  <th>Posisi</th>
			  <th>Deskripsi</th>
              <th>Link</th>
			  <th>Status</th>
              <th>Aksi</th>
			  <!-- <th>Aksi</th> -->
      	</thead>

      	<tbody>
      		@foreach ($listlowongan as $lowongan)
      		<tr>
	      		<td>{{ $lowongan->instansi }}<br>
		        <td>{{ $lowongan->posisi }}</td>
				<td>{{ $lowongan->deskripsi }}</td>
                
                <td>@if(! $lowongan->link == NULL)
                {{ HTML::link($lowongan->link) }}
                @else
                Tidak Ada Link
                @endif
                
                </td>
                
				<td>
					@if($lowongan->aktif == 1)
						{{"Lowongan Aktif"}}
					@else
						{{"Lowongan Tidak Aktif"}}
					@endif
				</td>
				
                <td>
                {{ link_to_route('operator.lowongan.edit', 'Edit', $lowongan->id, ['class' => 'btn btn-sm btn-primary']) }}
                {{ HTML::link('operator/lowongan/deactive/'.$lowongan->id, 'Deactive', ['class' => 'btn btn-sm btn-danger']) }}
                </td>
                
		     </tr>
			@endforeach
      	</tbody>
	</table>
    {{ link_to_route('operator.lowongan.create', 'ADD', null, ['class' => 'btn btn-primary']) }}

@stop

app/views/protected/operator/list_users.blade.php
@extends('protected.operator.master')

@section('title', 'List Users')

@section('content')

<h2>Registered Users</h2>
	<p>Here you would normally search for users but since this is just a demo, I'm listing all of them.</p>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>id</th>
	          <th>Email</th>
	          <th>First Name</th>
	          <th>Last Name</th>
              <th>Jurusan</th>
              <th>Tahun</th>
              <th>Minat Wirausaha</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($users as $user)
      		<tr>
	      		<td>{{ $user->alumni_id }}</td>
		        <td>{{ link_to_route('operator.profiles.show', $user->email, $user->id) }}<br>		        
		        </td>
		        <td>{{ $user->first_name}}</td>
		        <td>{{ $user->last_name}}</td>
                <td>{{ $user->nama }}</td>
                <td>{{ $user->recruitmentsekolah }}</td>
                <td>{{ $user->minatwirausaha }}</td>
                <td>{{ HTML::link('operator/decline/'.$user->alumni_id.'/'.$user->id, 'Remove', ['class' => 'btn btn-sm btn-danger']) }}</td>
		     </tr>
			@endforeach

      	</tbody>
	</table>

@stop

app/views/protected/operator/master.blade.php
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<title>@yield('title') - Operator - Basic Auth Sentry</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->


</head>
<body>

	<header>

		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">Basic Auth Sentry</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="{{ set_active_operator('operator') }}">{{ HTML::linkRoute('operator_dashboard','Home') }}</li>
		        <!-- <?php

/*<li class="{{ set_active_operator('operator') }}"><a href="/laravelauthsentry/public/operator">Home</a></li>*/

?> -->
  		        <li class="{{ set_active_operator('operator/profiles') }}">{{ HTML::link('operator/profiles', 'List User') }}</li>
		        <li class="{{ set_active_operator('operator/lowongan') }}">{{HTML::link('operator/lowongan','List Lowongan')}}</li>
                <li class="{{ set_active_operator('operator/pending') }}">{{ HTML::linkRoute('pendinguser','Pending Request') }}</li>
		      </ul>

		      <ul class="nav navbar-nav navbar-right">

		        <li>{{HTML::link('logout','Logout')}}</li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>




	</header>

	<div class="container">
		@yield('content')
	</div>

	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/protected/operator/operator_dashboard.blade.php
@extends('protected.operator.master')

@section('title', 'Operator Dashboard')

@section('content')

	@if (Session::has('flash_message'))
			<p>{{ Session::get('flash_message') }}</p>
	@endif


	<div class="jumbotron">
		<h1>Operator Page</h1>
		<p>This page is for operators only!</p>
	</div>


@stop

app/views/protected/operator/pending_users.blade.php
@extends('protected.operator.master')

@section('title', 'List Users')

@section('content')

<h2>Pending User Approval</h2>
	
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>id</th>
	          <th>Email</th>
	          <th>First Name</th>
	          <th>Last Name</th>
              <th>Jurusan</th>
              <th>Tahun</th>
              
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($users as $user)
      		<tr>
	      		<td>{{ $user->alumni_id }}</td>
		        <td>{{ link_to_route('operator.profiles.show', $user->email, $user->id) }}<br>		        
		        </td>
		        <td>{{ $user->first_name}}</td>
		        <td>{{ $user->last_name}}</td>
                <td>{{ $user->nama }}</td>
                <td>{{ $user->recruitmentsekolah }}</td>
                
                <td>{{ HTML::link('operator/approval/'.$user->alumni_id.'/'.$user->id, 'Approve', ['class' => 'btn btn-sm btn-info']) }}
                {{ HTML::link('operator/decline/'.$user->alumni_id.'/'.$user->id, 'Decline', ['class' => 'btn btn-sm btn-danger']) }}
                </td>
		     </tr>
			@endforeach

      	</tbody>
	</table>

@stop

app/views/protected/operator/show_user.blade.php
@extends('protected.operator.master')

@section('title', 'View Profile')

@section('content')

	<h1>{{ $user->first_name }}'s Profile</h1>
	<ul>
		<li>Account Type: {{ $user_group }}</li>
		<li>Email Address: {{ $user->email }}</li>
		<li>First Name: {{ $user->first_name }}</li>
		<li>Last Name: {{ $user->last_name }}</li>
	</ul>

	@if(Sentry::check())

		{{ link_to_route('operator.profiles.edit', 'Edit Profile', $user->id, ['class' => 'btn btn-primary']) }}

	@endif

@stop