app/routes.php
<?php

# CSRF Protection
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Static Pages. Redirecting admin so admin cannot access these pages.
Route::group(['before' => 'redirectAdmin'], function()
{
	Route::get('/', ['as' => 'home', 'uses' => 'PagesController@getHome']);
	Route::get('/about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
	Route::get('/contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
});

//belum dicobain
# Static Pages. Redirecting operator so operator cannot access these pages.
Route::group(['before' => 'redirectOperator'], function()
{
	Route::get('/', ['as' => 'home', 'uses' => 'PagesController@getHome']);
	Route::get('/about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
	Route::get('/contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
});

# Registration
Route::group(['before' => 'guest'], function()
{
	Route::get('/register', 'RegistrationController@create');
	Route::post('/register', ['as' => 'registration.store', 'uses' => 'RegistrationController@store']);
});

# Authentication
Route::get('login', ['as' => 'login', 'uses' => 'SessionsController@create'])->before('guest');
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
Route::resource('sessions', 'SessionsController' , ['only' => ['create','store','destroy']]);

# Forgotten Password //belum harus pake email. config>mail
Route::group(['before' => 'guest'], function()
{
	Route::get('forgot_password', 'RemindersController@getRemind');
	Route::post('forgot_password','RemindersController@postRemind');
	Route::get('reset_password/{token}', 'RemindersController@getReset');
	Route::post('reset_password/{token}', 'RemindersController@postReset');
});


# Alumni Routes
Route::group(['before' => 'auth|alumni'], function()
{
    //Route::get('/', ['as' => 'alumni_dashboard', 'uses' => 'AlumniController@getUserProtected']);
    Route::get('lowongan', ['as' => 'lowongan', 'uses' => 'AlumniController@getLowongan']);
    Route::get('sekolah', ['as' => 'sekolah', 'uses' => 'AlumniController@getSekolah']);
    Route::resource('profiles', 'AlumniUsersController', ['only' => ['show', 'edit', 'update']]);
    Route::get('profiles/{id}/editb', ['as' => 'editb', 'uses' => 'AlumniUsersController@editb']);
    Route::patch('profiles/{id}/updateb', ['as' => 'updateb', 'uses' => 'AlumniUsersController@updateb']);


});

# Admin Routes
Route::group(['before' => 'auth|admin'], function()
{
	Route::get('/admin', ['as' => 'admin_dashboard', 'uses' => 'AdminController@getHome']);

    Route::resource('admin/profiles', 'AdminUsersController', ['only' => ['index', 'show', 'edit', 'update', 'destroy','create','store']]);
    
    Route::resource('admin/sekolah', 'AdminSekolahController', ['only' => ['index', 'create','store','show','edit','update']]);

    Route::get('admin/jurusan/createoperator/{id}', array('as'=>'admin.jurusan.createoperator', 'uses' => 'AdminJurusanController@createOperator'));
    Route::post('admin/jurusan/storeoperator/{ids}', array('as'=>'admin.jurusan.storeoperator', 'uses'=>'AdminJurusanController@storeOperator'));
    Route::get('admin/jurusan/editoperator/{id}', array('as'=>'admin.jurusan.editoperator','uses' => 'AdminJurusanController@editOperator'));
    Route::patch('admin/jurusan/updateoperator/{id}', array('as'=>'admin.jurusan.updateoperator','uses' => 'AdminJurusanController@updateOperator'));
    Route::resource('admin/jurusan', 'AdminJurusanController', ['only' => ['show','edit','update']]);    
    Route::get('admin/jurusan/create/{id}', array('as'=>'admin.jurusan.create', 'uses' => 'AdminJurusanController@create'));
    Route::post('admin/jurusan/store/{id}', array('as'=>'admin.jurusan.store', 'uses'=>'AdminJurusanController@store'));
    Route::get('admin/jurusan/detail/{id}', array('as'=>'admin.jurusan.detail', 'uses' => 'AdminJurusanController@detail'));

    Route::resource('admin/alumni', 'AdminAlumniController', ['only' => ['show','edit','update']]);
    Route::get('admin/alumni/create/{id}', array('as'=>'admin.alumni.create', 'uses' => 'AdminAlumniController@create'));
    Route::post('admin/alumni/store/{id}', array('as'=>'admin.alumni.store', 'uses'=>'AdminAlumniController@store'));    
    Route::get('admin/alumni/detail/{id}', array('as'=>'admin.alumni.detail', 'uses' => 'AdminAlumniController@detail'));

    //ada bug kalo ditaro dibawah AdminLokerController@show
    Route::get('admin/loker/createglobal', array('as'=>'admin.loker.createglobal', 'uses' => 'AdminLokerController@createGlobal'));
    Route::post('admin/loker/storeglobal', array('as'=>'admin.loker.storeglobal', 'uses'=>'AdminLokerController@storeGlobal'));
    Route::resource('admin/loker', 'AdminLokerController', ['only' => ['index','show','edit','update']]);
    Route::get('admin/loker/create/{id}', array('as'=>'admin.loker.create', 'uses' => 'AdminLokerController@create'));
    Route::post('admin/loker/store/{id}', array('as'=>'admin.loker.store', 'uses'=>'AdminLokerController@store'));
    Route::get('admin/loker/detail/{id}', array('as'=>'admin.loker.detail', 'uses'=>'AdminLokerController@detail'));

});

# Operator Routes
Route::group(['before' => 'auth|operator'], function()
{
    Route::get('/operator', ['as' => 'operator_dashboard', 'uses' => 'OperatorController@getHome']);
    Route::resource('operator/profiles', 'OperatorUsersController', ['only' => ['index', 'show', 'edit', 'update', 'destroy']]);
    Route::resource('operator/lowongan', 'OperatorLowonganController', ['only' => ['index', 'create','store','show','edit','update']]);
    Route::get('operator/lowongan/deactive/{id}', ['as'=>'deactivelowongan', 'uses'=>'OperatorLowonganController@deactive']);
    Route::get('operator/pending', ['as'=>'pendinguser','uses'=>'OperatorUsersController@pending']);
    Route::get('operator/approval/{id}/{user}', ['as'=>'approveuser','uses'=>'OperatorUsersController@approval']);
    Route::get('operator/decline/{id}/{user}', ['as'=>'declineuser','uses'=>'OperatorUsersController@decline']);
});

app/views/protected/admin/create_alumni.blade.php
@extends('protected.admin.master')

@section('title', 'Tambah Alumni')

@section('content')


		<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Tambah Alumni - {{$datajurusan->nama}} - {{$datajurusan->sekolah->nama}}</h3>
				 	</div>
				  	<div class="panel-body">
				    	{{ Form::open(['method' => 'post', 'route' => ['admin.alumni.store', $datajurusan->id]]) }}
	                    <fieldset>
	                    	@if (Session::has('flash_message'))
								<div class="form-group">
									<p>{{ Session::get('flash_message') }}</p>
								</div>
							@endif

							<!-- MASUK KE TABEL USERS -->
							<div class="form-group">
								{{ Form::text('email', null, ['placeholder' => 'Email', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('email', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('username', null, ['placeholder' => 'Username', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('username', $errors) }}
							</div>

							<!-- Password field -->
							<div class="form-group">
								{{ Form::password('password', ['placeholder' => 'Password', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('password', $errors) }}
							</div>

							<!-- Password Confirmation field -->
							<div class="form-group">
								{{ Form::password('password_confirmation', ['placeholder' => 'Password Confirm', 'class' => 'form-control', 'required' => 'required'])}}

							</div>

							<!-- First name field -->
							<div class="form-group">
								{{ Form::text('fname', null, ['placeholder' => 'First Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('fname', $errors) }}
							</div>

							<!-- Last name field -->
							<div class="form-group">
								{{ Form::text('lname', null, ['placeholder' => 'Last Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('lname', $errors) }}
							</div>
							<!-- END TABEL USERS -->


							<!-- MASUK TABEL ALUMNI -->
							<div class="form-group">
								{{ Form::text('nis', null, ['placeholder' => 'NIS', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('nis', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('tanggallahir', null, ['placeholder' => 'Tanggal Lahir', 'class' => 'form-control'])}}
								{{ errors_for('tanggallahir', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('tempatlahir', null, ['placeholder' => 'Tempat Lahir', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('tempatlahir', $errors) }}
							</div>
							<div class="form-group">								
								{{ Form::select('gender', array('L' => 'Laki-laki', 'P' => 'Perempuan'), null, ['class' => 'form-control']) }}
								{{ errors_for('gender', $errors)}}
							</div>

							<div class="form-group">
								{{ Form::text('fb', null, ['placeholder' => 'Username Facebook', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('fb', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('nohp', null, ['placeholder' => 'Nomor HP', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('nohp', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('alamat', null, ['placeholder' => 'Alamat', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('alamat', $errors) }}
							</div>
							<div class="form-group">
								{{ Form::text('telepon', null, ['placeholder' => 'Telepon', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('telepon', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::text('recruitmentsekolah', null, ['placeholder' => 'Recruitment Sekolah', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('recruitmentsekolah', $errors) }}
							</div>
							<div class="form-group">								
								{{ Form::select('statusbekerja', array('1' => 'Sedang Bekerja', '0' => 'Tidak Bekerja'), null, ['class' => 'form-control']) }}
								{{ errors_for('statusbekerja', $errors)}}
							</div>

							<div class="form-group">
								{{ Form::text('kegiatankelompok', null, ['placeholder' => 'Kegiatan Kelompok', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('kegiatankelompok', $errors) }}
							</div>
							<div class="form-group">								
								{{ Form::select('minatwirausaha', array('1' => 'Saya Berminat Wirausaha', '0' => 'Saya Tidak Berminat Wirausaha'), null, ['class' => 'form-control']) }}
								{{ errors_for('minatwirausaha', $errors)}}
							</div>

							<div class="form-group">
								{{ Form::label('aktifform', 'Status Aktivasi:')}}
								{{ Form::select('aktifform', array('0' => 'Tidak Aktif', '1' => 'Aktif'), array('1'), ['class' => 'form-control']) }}
								{{ errors_for('aktifform', $errors)}}
							</div>

							<!-- Submit field -->
							<div class="form-group">
								{{ Form::submit('Tambah', ['class' => 'btn btn-lg btn-primary btn-block']) }}
								{{ HTML::link('admin/alumni'.$datajurusan->id, 'Back') }}
							</div>
				    	</fieldset>
				      	{{ Form::close() }}
				    </div>
				</div>
			</div>
		</div>
	</div>



@stop

app/views/protected/admin/create_jurusan.blade.php
@extends('protected.admin.master')

@section('title', 'Tambah Jurusan')

@section('content')


		<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Tambah Jurusan</h3>
				 	</div>
				  	<div class="panel-body">
				    	{{ Form::open(['method' => 'post', 'route' => ['admin.jurusan.store', $datasekolah->id]]) }}
	                    <fieldset>
	                    	@if (Session::has('flash_message'))
								<div class="form-group">
									<p>{{ Session::get('flash_message') }}</p>
								</div>
							@endif

							<div class="form-group">
								{{ Form::text('nama', null, ['placeholder' => 'Nama Jurusan', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('nama', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::label('aktifform', 'Aktivasi Jurusan:')}}
								{{ Form::select('aktifform', array('0' => 'Jurusan Tidak Aktif', '1' => 'Jurusan Aktif'), array('1'), ['class' => 'form-control']) }}
								{{ errors_for('aktifform', $errors)}}
							</div>

							<!-- Submit field -->
							<div class="form-group">
								{{ Form::submit('Tambah', ['class' => 'btn btn-lg btn-primary btn-block']) }}
								{{ HTML::link('admin/jurusan/'.$datasekolah->id, 'Back') }}
							</div>
				    	</fieldset>
				      	{{ Form::close() }}
				    </div>
				</div>
			</div>
		</div>
	</div>



@stop

app/views/protected/admin/create_jurusan_operator.blade.php
@extends('protected.admin.master')

@section('title', 'Tambah Operator')

@section('content')


		<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Tambah Operator - {{$datasekolah->nama}}</h3>
				 	</div>
				  	<div class="panel-body">
				    	{{ Form::open(array('route' => array('admin.jurusan.storeoperator', $datasekolah->id), 'method' => 'post' ))}}
	                    <fieldset>
	                    	@if (Session::has('flash_message'))
								<div class="form-group">
									<p>{{ Session::get('flash_message') }}</p>
								</div>
							@endif
							
							<div class="form-group">
								{{ Form::label('email', 'Email:')}}
								{{ Form::text('email', null, ['placeholder' => 'Email', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('email', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::label('username', 'Username:')}}
								{{ Form::text('username', null, ['placeholder' => 'Username', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('username', $errors) }}
							</div>

							<!-- Password field -->
							<div class="form-group">
								{{ Form::label('password', 'Password:')}}
								{{ Form::password('password', ['placeholder' => 'Password', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('password', $errors) }}
							</div>

							<!-- Password Confirmation field -->
							<div class="form-group">
								{{ Form::label('password_confirmation', 'Confirm Password:')}}
								{{ Form::password('password_confirmation', ['placeholder' => 'Password Confirm', 'class' => 'form-control', 'required' => 'required'])}}

							</div>

							<!-- First name field -->
							<div class="form-group">
								{{ Form::label('fname', 'First Name:')}}
								{{ Form::text('fname', null, ['placeholder' => 'First Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('fname', $errors) }}
							</div>

							<!-- Last name field -->
							<div class="form-group">
								{{ Form::label('lname', 'Last Name:')}}
								{{ Form::text('lname', null, ['placeholder' => 'Last Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('lname', $errors) }}
							</div>							

							<div class="form-group">
								{{ Form::label('aktifform', 'Status Aktivasi:')}}
								{{ Form::select('aktifform', array('0' => 'Tidak Aktif', '1' => 'Aktif'), array('1'), ['class' => 'form-control']) }}
								{{ errors_for('aktifform', $errors)}}
							</div>

							<!-- Submit field -->
							<div class="form-group">
								{{ Form::submit('Tambah', ['class' => 'btn btn-lg btn-primary btn-block']) }}
								{{ HTML::link('admin/jurusan/'.$datasekolah->id, 'Back') }}
							</div>
				    	</fieldset>
				      	{{ Form::close() }}
				    </div>
				</div>
			</div>
		</div>
	</div>



@stop

app/views/protected/admin/create_loker.blade.php
@extends('protected.admin.master')

@section('title', 'Tambah Lowongan Kerja')

@section('content')


		<div class="container">
	    <div class="row">
			<div class="col-md-6 col-md-offset-3">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Tambah Lowongan Kerja - {{$datasekolah->nama}}</h3>
				 	</div>
				  	<div class="panel-body">
				    	{{ Form::open(['method' => 'post', 'route' => ['admin.loker.store', $datasekolah->id]]) }}
	                    <fieldset>
	                    	@if (Session::has('flash_message'))
								<div class="form-group">
									<p>{{ Session::get('flash_message') }}</p>
								</div>
							@endif

							<div class="form-group">
								{{ Form::text('link', null, ['placeholder' => 'Link Web', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('link', $errors) }}
							</div>
							<div class="form-group">
								{{ Form::text('instansi', null, ['placeholder' => 'Instansi', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('instansi', $errors) }}
							</div>
							<div class="form-group">
								{{ Form::text('posisi', null, ['placeholder' => 'Posisi', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('posisi', $errors) }}
							</div>
							<div class="form-group">
								{{ Form::textarea('deskripsi', null, ['placeholder' => 'Deskripsi', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('deskripsi', $errors) }}
							</div>

							<div class="form-group">
								{{ Form::label('aktifform', 'Status Aktivasi:')}}
								{{ Form::select('aktifform', array('0' => 'Tidak Aktif', '1' => 'Aktif'), array('1'), ['class' => 'form-control']) }}
								{{ errors_for('aktifform', $errors)}}
							</div>

							<!-- Submit field -->
							<div class="form-group">
								{{ Form::submit('Tambah', ['class' => 'btn btn-lg btn-primary btn-block']) }}
								{{ HTML::link('admin/loker/'.$datasekolah->id, 'Back') }}
							</div>
				    	</fieldset>
				      	{{ Form::close() }}
				    </div>
				</div>
			</div>
		</div>
	</div>



@stop

app/views/protected/admin/list_loker.blade.php
@extends('protected.admin.master')

@section('title', 'List Lowongan Kerja')

@section('content')
	<h1>{{ $datasekolah->nama }}</h1>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>ID</th>
	          <th>Link</th>
			  <th>Instansi Loker</th>
			  <th>Posisi</th>
			  <th>Deskripsi</th>
			  <th>Dibuat</th>
			  <th>Diupdate</th>
			  <th>Aktivasi</th>
			  <th>Aksi</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($listloker as $loker)
      		<tr>
      			<td>{{ $loker->id}}</td>
	      		<td><a href="{{ $loker->link }}">Link</a></td>
		        <td>{{ $loker->instansi}} </td>
				<td>{{ $loker->posisi }}</td>
				<td>{{ $loker->deskripsi }}</td>
				<td>{{{ date('d-m-Y H:i:s', strtotime($loker->created_at)) }}}</td>
				<td>{{{ date('d-m-Y H:i:s', strtotime($loker->updated_at)) }}}</td>
				<td>
					@if($loker->aktif == 1)
						{{"Loker Aktif"}}
					@else
						{{"Loker Tidak Aktif"}}
					@endif
				</td> 
				<td>{{ link_to_route('admin.loker.edit', 'Edit', $loker->id, ['class' => 'btn btn-primary']) }}
					{{ link_to_route('admin.loker.detail', 'Details', $loker->id, ['class' => 'btn btn-primary']) }}
				</td>
		     </tr>
			@endforeach
      	</tbody>
	</table>
	@if(Sentry::check())

		{{ link_to_route('admin.loker.create', 'Tambah', $datasekolah->id, ['class' => 'btn btn-primary']) }}
					
	@endif
	{{ HTML::link('admin/loker', 'Back', ['class' => 'btn btn-primary']) }}
@stop

app/views/protected/admin/list_sekolah.blade.php
@extends('protected.admin.master')

@section('title', 'List Sekolah')

@section('content')

<h2>Daftar Sekolah</h2>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>Nama</th>
			  <th>Logo</th>
			  <th>Alamat</th>
			  <th>Status</th>
			  <th>Aksi</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($listsekolah as $sekolah)
      		<tr>
	      		<td>{{ link_to_route('admin.jurusan.show', $sekolah->nama, $sekolah->id) }}<br>
		        <td>{{HTML::image("$sekolah->logo", $alt="$sekolah->nama", $attributes = array())}}</td>
				<td>{{ $sekolah->alamat }}</td>
				<td>
					@if($sekolah->aktif == 1)
						{{"Sekolah Aktif"}}
					@else
						{{"Sekolah Tidak Aktif"}}
					@endif
				</td>
				<td>{{ link_to_route('admin.sekolah.edit', 'Edit', $sekolah->id, ['class' => 'btn btn-primary']) }}
					{{ link_to_route('admin.sekolah.show', 'Details', $sekolah->id, ['class' => 'btn btn-primary']) }}
				</td>
		     </tr>
			@endforeach
      	</tbody>
	</table>
	
			{{ link_to_route('admin.sekolah.create', 'Tambah', null, ['class' => 'btn btn-primary']) }}

@stop

app/views/protected/admin/list_sekolah_loker.blade.php
@extends('protected.admin.master')

@section('title', 'Lowongan Kerja')

@section('content')
<div>
<h2>Daftar Sekolah</h2>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>Nama</th>
			  <!--<th>Logo</th>-->
			  <th>Alamat</th>
			  <th>Jumlah Loker(Aktif+Tidak Aktif)</th>
			  <th>Aksi</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($datasekolah as $sekolah)
      		<tr>
	      		<td>{{ $sekolah->nama }}<br>
		        <!--<td>{{HTML::image("$sekolah->logo", $alt="$sekolah->nama", $attributes = array())}}</td>-->
				<td>{{ $sekolah->alamat }}</td>
				<td>{{count($sekolah->lowongankerja)}}</td>
				<td>{{ link_to_route('admin.loker.show', 'Lihat Loker', $sekolah->id, ['class' => 'btn btn-primary']) }}
				</td>
		     </tr>
			@endforeach
      	</tbody>
	</table>
</div>

<div>
<h2>Daftar Lowongan Kerja</h2>
	<table class="table table-striped table-bordered table-hover">
		<thead>
	        <tr>
	          <th>ID</th>
	          <th>Sekolah</th>
	          <th>Link</th>
			  <th>Instansi Loker</th>
			  <th>Posisi</th>
			  <th>Deskripsi</th>
			  <th>Status</th>
			  <th>Aksi</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($listloker as $loker)
      		<tr>
      			<td>{{$loker->id}}</td>
	      		<td>{{ $loker->sekolah->nama }}</td>
	      		<td><a href="{{$loker->link}}">Link</a></td>
		        <td>{{ $loker->instansi}} </td>
				<td>{{ $loker->posisi }}</td>
				<td>{{ $loker->deskripsi }}</td>
				<td>
					@if($loker->aktif == 1)
						{{"Loker Aktif"}}
					@else
						{{"Loker Tidak Aktif"}}
					@endif
				</td> 
				<td>{{ link_to_route('admin.loker.edit', 'Edit', $loker->id, ['class' => 'btn btn-primary']) }}
					{{ link_to_route('admin.loker.detail', 'Details', $loker->id, ['class' => 'btn btn-primary']) }}
				</td>
		     </tr>
			@endforeach
      	</tbody>
	</table>	
			{{ link_to_route('admin.loker.createglobal', 'Tambah', null, ['class' => 'btn btn-primary']) }}
</div>

@stop

app/views/protected/admin/show_sekolah.blade.php
@extends('protected.admin.master')

@section('title', 'View Sekolah')

@section('content')

	<h1>{{ $listsekolah->nama }}'s Profile 
	@if($listsekolah->logo)
	{{HTML::image("$listsekolah->logo", $alt="$listsekolah->nama", array( 'width' => 70, 'height' => 70 ))}}
	@endif
	</h1>
	<ul>
		<li>ID: {{$listsekolah->id}}</li>
		<li>Nama: {{ $listsekolah->nama }}</li>
		<li>Logo: {{ $listsekolah->logo }}</li>
		<li>Alamat: {{ $listsekolah->alamat }}</li>
		<li>Telepon: {{ $listsekolah->telepon }}</li>
		<li>Akreditasi: {{ $listsekolah->akreditasi }}</li>
		<li>Jumlah Pengajar: {{ $listsekolah->jml_pengajar }}</li>
		<li>Deskripsi: {{ $listsekolah->deskripsi }}</li>
		<li>Created By: {{ $listsekolah->sekolahcreatedby->username }}</li>
		<li>Last Modified By: {{$listsekolah->sekolahmodifiedby->username}}</li>
		<li>Aktivasi: 
			@if($listsekolah->aktif == 1)
				{{"Sekolah Aktif"}}
			@else
				{{"Sekolah Tidak Aktif"}}
			@endif
		</li> 
	</ul>

	@if(Sentry::check())

		{{ link_to_route('admin.sekolah.edit', 'Edit', $listsekolah->id, ['class' => 'btn btn-primary']) }}
					
	@endif
	{{ HTML::link('admin/sekolah/', 'Back') }}

@stop